# ~/.config/starship.toml

# no newline
add_newline = false

# change the prompt character
[character]
symbol = "ğŸƒ"
#"ğŸŒŠ"
error_symbol = "âœ—"

# directory prompt
[directory]
prefix = "dir "
style = "bold cyan"

# username module
#[username]
#show_always = true
#style_user = "bright-cyan"
